### ISSUE TITLE
Authorship clarification

### ISSUE THREAD

**Issue by malcolmbarrett** [meantrix/corrp#8]
In openjournals/joss-reviews#7319, @PHS-Meantrix is listed as the submitting author and an author on the paper. In the `DESCRIPTION` file, @igor-siciliani together with `Meantrix <dev@meantrix.com>`. Should @PHS-Meantrix be an author or contributed? I also believe that Meantrix should be the copyright holder, not the maintainer. See this example from Posit of how to list authors and companies https://github.com/r-lib/usethis/blob/main/DESCRIPTION

**Comment by jromanowska** [comment]
Very good point! However, in JOSS, the authors on the paper should be those who contributed to the code in the repo. Thus, the author list is fine. Let's see what the authors say about the items in `DESCRIPTION` .

**Comment by igor-siciliani** [comment]
This was done by @PHS-Meantrix
